apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-dummy-node-app
spec:
  replicas: 3
  selector:
    app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy-node-app
          image: tommystark/dummy-node-app
          ports:
            - containerPort: 8080
              protocol: TCP


