apiVersion: v1
kind: Pod
metadata:
  name: dummy-node-app-with-labels
  labels:
    env: test
    creation_method: manual
spec:
  containers:
  - image: tommystark/dummy-node-app
    name: dummy-node-app
    ports:
    - containerPort: 8080
      protocol: TCP
