apiVersion: v1
kind: Pod
metadata:
  name: dummy-node-app-node-selector
spec:
  nodeSelector:
    random: "true"
  containers:
  - image: tommystark/dummy-node-app
    name: dummy-node-app
    ports:
    - containerPort: 8080
      protocol: TCP
