apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  containers:
  - image: tommystark/fortune
    name: fortune-app
    env:
    - name: SLEEP_INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
      - name: html
        mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
      # You configured Nginx to read the cert and key file from /etc/nginx/certs, so you need to mount the Secret volume there.
      - name: certs
        mountPath: /etc/nginx/certs
        readOnly: true
      - name: config
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: https.conf
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
  volumes:
  - name: certs
    secret:
      secretName: fortune-https
  - name: config
    configMap:
      name: fortune-config
      # Setting file permissions
      defaultMode: 0660
      items:
      - key: nginx-https.conf
        path: https.conf
  - name: html
    emptyDir: {}
