apiVersion: v1
kind: Pod
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  containers:
  - image: tommystark/fortune
    name: fortune-app
    env:
    - name: SLEEP_INTERVAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    volumeMounts:
      - name: html
        mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d/default.conf
        subPath: gzip.conf
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    ports:
        - containerPort: 80
          protocol: TCP
  volumes:
  - name: config
    configMap:
      name: fortune-config
      # Setting file permissions
      defaultMode: 0660
      items:
      - key: nginx-gzip.conf
        path: gzip.conf
  - name: html
    emptyDir: {}
