apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pvc
spec:
  containers:
    - name: mongodb
      image: mongo
      ports:
      - containerPort: 21017
        protocol: TCP
      volumeMounts:
      - name: mongodb-data
        # path were mongodb store its daata
        mountPath: /data/db
  volumes:
  - name: mongodb-data
    # Referencing the PersistentVolumeClaim by name in the pod volume
    persistentVolumeClaim:
      claimName: mongodb-pvc
