apiVersion: v1
kind: Pod
metadata:
  name: dummy-node-app-with-liveness-probe
spec:
  containers:
  - image: tommystark/dummy-node-app
    name: dummy-liveness-probe
    command: ["node"]
    args: ["app.js", "liveness-probe-test"]
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 2
    startupProbe:
      httpGet:
        path: /
        port: 8080
      # When a probe fails, Kubernetes will try failureThreshold times before giving up. 
      # Giving up in case of liveness probe means restarting the container. 
      # In case of readiness probe the Pod will be marked Unready.
      failureThreshold: 5
      periodSeconds: 1
