apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dummy-node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: dummy-node-app
        image: tommystark/dummy-node-app
