apiVersion: v1
kind: Service
metadata:
  name: headless-service-dummy-node-app
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: dummy
